name = "lexis-publisher"
main = "src/index.js"
compatibility_date = "2024-03-20"


# Vamos usar variáveis de ambiente para o Token do GitHub (segurança primeiro!)
[vars]
GITHUB_OWNER = "lexisvirtual"
GITHUB_REPO = "lexis3"
GITHUB_BRANCH = "main"

# Habilitar Workers AI
[ai]
binding = "AI"

# Conectar Banco de Dados KV (Pauta)
[[kv_namespaces]]
binding = "LEXIS_PAUTA"
id = "071364560008455bad2f86d070c9f4bd"

# Agendamento Automático (CRON)
# Roda todo dia às 09:00 UTC (06:00 BRT)
[triggers]
crons = ["0 9 * * *"]

